### ISSUE TITLE
Imgur is temporarily over capacity. Please try again later.

### ISSUE THREAD

**Issue by huakairuoxiangxi** [hackmdio/hackmd#234] opened 2016-10-24 13:39 UTC
i set Imgur client id, but have this error.
Imgur is temporarily over capacity. Please try again later.

**Comment by jackycute** [comment] 2016-10-24 13:46
Hi @huakairuoxiangxi 
Could you please paste your config file? or you set it via the environment variable?
This might be a temporarily error from imgur, just wait and we might have nothing can do about it.

**Comment by huakairuoxiangxi** [comment] 2016-10-25 04:27
https://api.imgur.com/oauth2/addclient  =>  chose Anonymous usage without user authorization
Authorization callback URL: What should be input？

my config.json

"production": {
        "urladdport":true,
        "domain": "xxxxx.com",
	"port":"80",
        "db": {
            "username": "hackmd",
            "password": "hackmdpass",
            "database": "hackmd",
            "host": "hackmdPostgres",
            "port": "5432",
            "dialect": "postgres"
        },
        "github":{
            "clientID":"xxxxx",
            "clientSecret":"xxxxxxxxx"
        },
	"imgur":{
	    "clientID":"4fd6xxxxx8da54"
	}
    }
}

**Comment by jackycute** [comment] 2016-10-25 04:32
Just leave Authorization callback URL as empty.
Your config is fine.

**Comment by huakairuoxiangxi** [comment] 2016-10-25 04:48
Authorization callback URL can't empty.  
will this be affected？

**Comment by jackycute** [comment] 2016-10-25 04:51
It definitely be there webpage bug.
The Authorization callback URL is not required in "Anonymous usage without user authorization".
You must click around all options and choose "Anonymous usage without user authorization, then go on.

**Comment by huakairuoxiangxi** [comment] 2016-10-25 05:08
still have a problem：Imgur is temporarily over capacity. Please try again later. 

i am install     "imgur": "git+https://github.com/hackmdio/node-imgur.git",
└> imgur --save 7f4e8443b282a2d
└> imgur test.jpg 
Imgur is temporarily over capacity. Please try again later. (tsrc.jpg)

**Comment by jackycute** [comment] 2016-10-25 05:13
I just try on my own server and official service.
Imgur are both fine here.

Could you try upload on http://imgur.com ?
Maybe your country IP have been banned or some.

**Comment by jackycute** [comment] 2016-10-25 05:14
Also the imgur status showed here http://status.imgur.com/

**Comment by huakairuoxiangxi** [comment] 2016-10-25 05:17
you are right. i can open website,but can't upload image in china.

**Comment by jackycute** [comment] 2016-10-25 05:20
I'm sorry to hear that.
Well, we'll support local or S3 uploading in the future, see #156

**Comment by huakairuoxiangxi** [comment] 2016-10-25 06:04
i want to store in localhost in the future

**Comment by jackycute** [comment] 2016-10-25 07:06
localhost image upload will be included in #156, so keep eye on it.
Will close this issue now.

**Closed by jackycute** 2016-10-25 07:06 UTC

**Comment by huakairuoxiangxi** [comment] 2016-10-25 18:51
Authorization callback URL can't empty.
will this be affected？



2016-10-25 12:32 GMT+08:00 Max Wu <notifications@github.com>:

**Comment by jackycute** [comment] 2016-10-26 05:43
@huakairuoxiangxi no it won't.

**Comment by katelynnfitz** [comment] 2022-08-25 03:28
It did this to me soon as I enabled a proxy so that may be the cause.

**Comment by katelynnfitz** [comment] 2022-08-25 03:29
{"data":{"error":"Imgur is temporarily over capacity. Please try again later."},"success":false,"status":403}

**Comment by josieforever** [comment] 2022-11-15 06:34
I am getting this error anytime I use the oauth2 verification on imgur
{"data":{"error":"Imgur is temporarily over capacity. Please try again later."},"success":false,"status":403}

**Comment by BlerionMuco** [comment] 2022-12-06 20:47
> I am getting this error anytime I use the oauth2 verification on imgur {"data":{"error":"Imgur is temporarily over capacity. Please try again later."},"success":false,"status":403}

Hey there hope you are doing okay i dont know if this is your case but dont use localhost. 
try to replace it with your Id address so for example from http://localhost:3000 to http://192.X.X.X:3000 for me this worked

**Comment by techlantis** [comment] 2022-12-29 21:29
> > I am getting this error anytime I use the oauth2 verification on imgur {"data":{"error":"Imgur is temporarily over capacity. Please try again later."},"success":false,"status":403}
> 
> Hey there hope you are doing okay i dont know if this is your case but dont use localhost. try to replace it with your Id address so for example from http://localhost:3000 to http://192.X.X.X:3000 for me this worked

Amazing! This worked thanks.

**Comment by qzw881130** [comment] 2023-10-24 18:12
> > I am getting this error anytime I use the oauth2 verification on imgur {"data":{"error":"Imgur is temporarily over capacity. Please try again later."},"success":false,"status":403}
> 
> Hey there hope you are doing okay i dont know if this is your case but dont use localhost. try to replace it with your Id address so for example from http://localhost:3000 to http://192.X.X.X:3000 for me this worked

Nice!
i  solved it with ngrok.

**Comment by wesley-surt** [comment] 2023-12-27 21:42
Reparei que alguém deu a dica para coloca esta url http://192.x.x.x:3000/ ao invés de usar o localhost. Usando esta url no formato que está sendo apresentada já é suficiente para talvez resolver meu problema? Ou devo alterar o número pelo ip da minha máquina?

**Comment by BlerionMuco** [comment] 2023-12-29 19:00
> Reparei que alguém deu a dica para coloca esta url http://192.x.x.x:3000/ ao invés de usar o localhost. Usando esta url no formato que está sendo apresentada já é suficiente para talvez resolver meu problema? Ou devo alterar o número pelo ip da minha máquina?

Hello there, if you have not solve the problem yet...
You need to check your machine ip. 
In windows terminal press **ipconfig**
In Mac terminal press ** ifconfig**
After finding the ip, replace on the url.

Blerion

**Comment by Mateusinhodev** [comment] 2025-03-14 00:37
> Olá, espero que esteja tudo bem. Não sei se é o seu caso, mas não use o localhost. Tente substituí-lo pelo seu endereço de ID, por exemplo, de http://localhost:3000 a [http://192.XXX:3000](http://192.X.X.X:3000) (seu endereço IP da máquina). Para mim, isso funcionou.

Deu certo aqui, salvou demais!!!
