### ISSUE TITLE
Editor Toolbar

### ISSUE THREAD

**Issue by davidmehren** [hackmdio/hackmd#523] opened 2017-07-29 21:17 UTC
Hi!
I noticed that the hosted version on hackmd.io features a toolbar in the editor, for text fomatting, inserting images etc.
This feature does not seem to be present in version 0.5.1.
Is it going to be included in a later version? Is it an exclusive feature for hackmd.io?
Thanks for the info.

**Comment by MartB** [comment] 2017-08-07 11:53
Duplicate of https://github.com/hackmdio/hackmd/issues/375

**Comment by KrzysztofMadejski** [comment] 2017-09-12 19:04
So this issue should be closed. @davidmehren ?

**Closed** 2017-10-06 21:08 UTC
Labels: duplicate
