### ISSUE TITLE
sandstorm integration

### ISSUE THREAD

**Issue by zeigerpuppy** [hackmdio/hackmd#465] opened 2017-05-24 06:13 UTC
hackmd would be really great to work into a sandstorm app.
There is a guide on this here: https://docs.sandstorm.io/en/latest/developing/raw-packaging-guide/

Sandstrom makes sharing documents much easier for users.
I'd be happy to test/collaborate on porting

**Comment by jackycute** [comment] 2017-05-31 16:33
Hi @zeigerpuppy 
This might be great idea!
Welcome any PRs 😄

**Comment by zeigerpuppy** [comment] 2017-06-03 15:27
I have got a fair way down the track of building a sandstorm package, but have hit a few problems:

1. how do i set it up to use local storage instead of imgur (I could see references to using local uploads but am not sure of the config in config.json)?
2. I am having problems with the the `webpack` process in the build.  It seems to take ages trying to build and then fails. 

I have documented the build here: https://github.com/zeigerpuppy/hackmd/wiki

The log shows:
```
> hackmd@0.5.1 build /opt/app
> webpack --config webpack.production.js --progress --colors

 90% optimize assets
Starting to optimize CSS...
Processing html.min.css...
Processed html.min.css, before: 23230, after: 17479, ratio: 75.24%
 78% additional chunk assetsWARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
```

**Comment by SISheogorath** [comment] 2017-06-03 15:55
From my experience with the docker builds you need at least 2GB better 4GB of RAM.

Currently, the builds from TravisCI are fine. while the second build on a 2GB machine on DO had a broken version inside.

**Comment by zeigerpuppy** [comment] 2017-06-04 03:01
OK, thanks for the tip, I'll try upping the RAM in the vagrant VM...

**Comment by zeigerpuppy** [comment] 2017-06-04 06:53
I got webpack to build once using 4GB of ram in the VM.
However, when I try to build again with exactly the same VM, it fails.  I was monitoring via `top` and memory never ran out but did get quite low.

Perhaps it needs even more RAM!

here's the log:
```
> hackmd@0.5.1 build /opt/app
> webpack --config webpack.production.js --progress --colors

 90% optimize assets
Starting to optimize CSS...
Processing html.min.css...
Processed html.min.css, before: 23230, after: 17479, ratio: 75.24%
 78% additional chunk assetsWARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
 95% emitError: ENOMEM: not enough memory, open '/opt/app/public/build/reveal.js/css/print/paper.css'
    at Error (native)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! hackmd@0.5.1 build: `webpack --config webpack.production.js --progress --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hackmd@0.5.1 build script 'webpack --config webpack.production.js --progress --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hackmd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config webpack.production.js --progress --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hackmd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hackmd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/app/npm-debug.log
Connection to 127.0.0.1 closed.
Traceback (most recent call last):
  File "/usr/local/bin/vagrant-spk", line 826, in <module>
    main()
  File "/usr/local/bin/vagrant-spk", line 823, in main
    operation(args)
  File "/usr/local/bin/vagrant-spk", line 612, in dev
    "spk dev --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef"
  File "/usr/local/bin/vagrant-spk", line 226, in call_vagrant_command
    return subprocess.check_call(command, cwd=sandstorm_dir)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['vagrant', 'ssh', '-c', '/opt/app/.sandstorm/build.sh && cd /opt/app/.sandstorm && spk dev --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef']' returned non-zero exit status 1****
```

**Comment by SISheogorath** [comment] 2017-06-04 09:44
Can you try to build it with the `--bail` parameter like: https://github.com/hackmdio/hackmd/pull/478

It should give you more detailed, why it fails.

Also by "There is free memory": What amount of memory are we talking about?

**Comment by zeigerpuppy** [comment] 2017-06-05 05:15
OK I have tried with the `--bail` parameter.
I also took it onto a more capable machine and gave the VM 20GB of RAM and 20 vcps.
The webpack process still fails (peak memory usage is 4.7GB)

Here's the log output:

```
> hackmd@0.5.1 build /opt/app
> webpack --config webpack.production.js --progress --colors --bail

 70% 16/16 b  0% compileModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' /opt/app/node_modules/codemirror/codemirror.min.js in /opt/app
    at /opt/app/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/opt/app/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /opt/app/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /opt/app/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /opt/app/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/opt/app/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /opt/app/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /opt/app/node_modules/webpack/node_modules/async/lib/async.js:723:17
    at /opt/app/node_modules/webpack/node_modules/async/lib/async.js:167:37
    at /opt/app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/opt/app/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at innerCallback (/opt/app/node_modules/enhanced-resolve/lib/Resolver.js:88:19)
    at loggingCallbackWrapper (/opt/app/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /opt/app/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/opt/app/node_modules/enhanced-resolve/lib/DirectoryDescriptionFileFieldAliasPlugin.js:75:26)
    at /opt/app/node_modules/enhanced-resolve/lib/DirectoryDescriptionFileFieldAliasPlugin.js:52:26
    at Storage.finished (/opt/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /opt/app/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
resolve file
  /opt/app/node_modules/codemirror/codemirror.min.js doesn't exist
  /opt/app/node_modules/codemirror/codemirror.min.js.js doesn't exist
resolve directory
  /opt/app/node_modules/codemirror/codemirror.min.js doesn't exist (directory default file)
  /opt/app/node_modules/codemirror/codemirror.min.js/package.json doesn't exist (directory description file)
 90% optimize assets
Starting to optimize CSS...
Processing html.min.css...
Processed html.min.css, before: 23230, after: 17479, ratio: 75.24%
 70% 1169/1169 build modules
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! hackmd@0.5.1 build: `webpack --config webpack.production.js --progress --colors --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hackmd@0.5.1 build script 'webpack --config webpack.production.js --progress --colors --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hackmd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config webpack.production.js --progress --colors --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hackmd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hackmd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/app/npm-debug.log
Connection to 127.0.0.1 closed.
Command failed with a non-zero exit status (1).
```

**Comment by zeigerpuppy** [comment] 2017-06-05 05:55
Following these errors, I tried installing and symlinking the miniified .css and .js files from `codemirror-minified` package from within the virtual machine:

```
ln -s /usr/lib/node_modules/codemirror-minified/lib/codemirror.css /opt/app/node_modules/codemirror/codemirror.min.js
ln -s /usr/lib/node_modules/codemirror-minified/lib/codemirror.css /opt/app/node_modules/codemirror/codemirror.min.css
```
That fixed the first part of the error: `Error: Cannot resolve 'file' or 'directory' /opt/app/node_modules/codemirror/codemirror.min.js in /opt/app` 

Which is one step closer, but it still bails out, this time at 'open '/opt/app/public/build/reveal.js/css/theme/beige.css''

I'm starting to this the issues may be from a malformed path but am still a bit stuck.

latest logs:

console:
```
install npm packages
npm WARN lifecycle hackmd@0.5.1~postinstall: cannot run in wd %s %s (wd=%s) hackmd@0.5.1 bin/heroku /opt/app
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN grunt-contrib-jshint@1.1.0 requires a peer of grunt@>=0.4.0 but none was installed.


Edit the following config file to setup hackmd server and client.
Read more info at https://github.com/hackmdio/hackmd#configuration-files

* config.json           -- server config
* public/js/config.js   -- client config
* .sequelizerc          -- db config


> hackmd@0.5.1 build /opt/app
> webpack --config webpack.production.js --progress --colors --bail

 90% optimize assets
Starting to optimize CSS...
Processing html.min.css...
Processed html.min.css, before: 23230, after: 17479, ratio: 75.24%
 78% additional chunk assetsWARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
 95% emitError: ENOMEM: not enough memory, open '/opt/app/public/build/reveal.js/css/theme/beige.css'
    at Error (native)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! hackmd@0.5.1 build: `webpack --config webpack.production.js --progress --colors --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hackmd@0.5.1 build script 'webpack --config webpack.production.js --progress --colors --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hackmd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config webpack.production.js --progress --colors --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hackmd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hackmd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/app/npm-debug.log
Connection to 127.0.0.1 closed.
Command failed with a non-zero exit status (1).
```

npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle hackmd@0.5.1~prebuild: hackmd@0.5.1
6 silly lifecycle hackmd@0.5.1~prebuild: no script for prebuild, continuing
7 info lifecycle hackmd@0.5.1~build: hackmd@0.5.1
8 verbose lifecycle hackmd@0.5.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle hackmd@0.5.1~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/opt/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle hackmd@0.5.1~build: CWD: /opt/app
11 silly lifecycle hackmd@0.5.1~build: Args: [ '-c',
11 silly lifecycle   'webpack --config webpack.production.js --progress --colors --bail' ]
12 silly lifecycle hackmd@0.5.1~build: Returned: code: 1  signal: null
13 info lifecycle hackmd@0.5.1~build: Failed to exec build script
14 verbose stack Error: hackmd@0.5.1 build: `webpack --config webpack.production.js --progress --colors --bail`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid hackmd@0.5.1
16 verbose cwd /opt/app
17 error Linux 3.16.0-4-amd64
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error hackmd@0.5.1 build: `webpack --config webpack.production.js --progress --colors --bail`
22 error Exit status 1
23 error Failed at the hackmd@0.5.1 build script 'webpack --config webpack.production.js --progress --colors --bail'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the hackmd package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack --config webpack.production.js --progress --colors --bail
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs hackmd
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls hackmd
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by SISheogorath** [comment] 2017-06-05 09:33
What base OS are you using? Because it sounds like there is some kind of memory limit for `webpack` and what platform? x86_64?

There are only two explanations for this:

1. There is a memory limit for webpack or during the process
2. The error message is wrong. In this case it's an upstream bug

Let me explain why I go for the first: Because most people here can build HackMD without a problem, so in general it works like it should. And it is something that is uncommon on your setup. Maybe you can share the vagrant file to let us reproduce your problem.

**Comment by JJediny** [comment] 2017-06-05 23:03
I encountered the exact issue when using both `nvm install 7` & `nvm install 6` only when I used `nvm install lts/boron` did `codemirror` successfully install and webpack complete. I failed to c/p output from the failed webpack runs; but it was failing when trying to use yaml.js. Sorry I couldn't post the exact output, but figured I'd call out what I saw

**Comment by JJediny** [comment] 2017-06-06 08:50
```
2017-06-06T04:25:45.08-0400 [STG/0] OUT -----> Building dependencies
2017-06-06T04:25:45.09-0400 [STG/0] OUT        Prebuild detected (node_modules already exists)
2017-06-06T04:25:45.09-0400 [STG/0] OUT        Rebuilding any native modules
2017-06-06T04:25:49.43-0400 [STG/0] OUT
2017-06-06T04:25:49.43-0400 [STG/0] OUT        > codemirror@5.25.1 install /tmp/app/node_modules/codemirror
2017-06-06T04:25:49.43-0400 [STG/0] OUT        > npm run-script build && ./release.sh
2017-06-06T04:25:49.43-0400 [STG/0] OUT
2017-06-06T04:25:50.12-0400 [STG/0] OUT
2017-06-06T04:25:50.12-0400 [STG/0] OUT        > codemirror@5.25.1 build /tmp/app/node_modules/codemirror
2017-06-06T04:25:50.12-0400 [STG/0] OUT        > rollup -c
2017-06-06T04:25:50.12-0400 [STG/0] OUT
2017-06-06T04:25:50.13-0400 [STG/0] OUT        sh: 1: rollup: not found
2017-06-06T04:25:50.13-0400 [STG/0] OUT
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! Linux 4.4.0-78-generic
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! argv "/tmp/app/.cloudfoundry/0/node/bin/node" "/tmp/app/.cloudfoundry/0/bin/npm" "run-scrip
t" "build"
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! node v7.10.0
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! npm  v4.2.0
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! file sh
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! code ELIFECYCLE
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! errno ENOENT
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! syscall spawn
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! codemirror@5.25.1 build: `rollup -c`
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! spawn ENOENT
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR!
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! Failed at the codemirror@5.25.1 build script 'rollup -c'.
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! If you do, this is most likely a problem with the codemirror package,
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! not with npm itself.
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! Tell the author that this fails on your system:
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR!     rollup -c
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! You can get information on how to open an issue for this project with:
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR!     npm bugs codemirror
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! Or if that isn't available, you can get their info via:
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR!     npm owner ls codemirror
2017-06-06T04:25:50.14-0400 [STG/0] OUT        npm ERR! There is likely additional logging output above.
2017-06-06T04:25:50.16-0400 [STG/0] OUT
2017-06-06T04:25:50.17-0400 [STG/0] OUT        npm ERR! Please include the following file with any support request:
2017-06-06T04:25:50.17-0400 [STG/0] OUT        npm ERR!     /home/vcap/.npm/_logs/2017-06-06T08_25_50_148Z-debug.log
```

**Comment by SISheogorath** [comment] 2017-06-06 11:37
@JJediny That's another error. `sh: 1: rollup: not found` tells you that there is the shebang statement in this script. Check the first line of `./node_modules/.bin/rollup -c`.

Iirc I had this issue, too, and fixed it by installing `bash`.

**Comment by zeigerpuppy** [comment] 2017-06-07 02:52
@SISheogorath, to answer your query, the build machine is running OS X El Capitan and the virtual machine which is being built is running Debian Jessie (this is the standard build environment for sandstorm packages: via vagrant, with Virtualbox images).  I think being in a virtual machine may be exposing some issues with paths, but feels like it's getting closer!
Thankfully once it's built once, it's really easy to then distribute the package for all sandstorm users.


Thanks @JJediny,  looks like `rollup` was missing altogether!
I guess it should be added to the `packages.json` file but I have put it in my `.sandstorm/build.sh` for the moment...

It's still not building but at least it gost past rollup this time...

console log:
```
> hackmd@0.5.1 build /opt/app
> webpack --config webpack.production.js --progress --colors --bail

 90% optimize assets
Starting to optimize CSS...
Processing html.min.css...
Processed html.min.css, before: 23230, after: 17479, ratio: 75.24%
 78% additional chunk assetsWARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
 95% emitError: ENOMEM: not enough memory, open '/opt/app/public/build/reveal.js/css/reveal.scss'
    at Error (native)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! hackmd@0.5.1 build: `webpack --config webpack.production.js --progress --colors --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hackmd@0.5.1 build script 'webpack --config webpack.production.js --progress --colors --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hackmd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config webpack.production.js --progress --colors --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hackmd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hackmd
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /opt/app/npm-debug.log
Connection to 127.0.0.1 closed.
Command failed with a non-zero exit status (1).
```
npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle hackmd@0.5.1~prebuild: hackmd@0.5.1
6 silly lifecycle hackmd@0.5.1~prebuild: no script for prebuild, continuing
7 info lifecycle hackmd@0.5.1~build: hackmd@0.5.1
8 verbose lifecycle hackmd@0.5.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle hackmd@0.5.1~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/opt/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle hackmd@0.5.1~build: CWD: /opt/app
11 silly lifecycle hackmd@0.5.1~build: Args: [ '-c',
11 silly lifecycle   'webpack --config webpack.production.js --progress --colors --bail' ]
12 silly lifecycle hackmd@0.5.1~build: Returned: code: 1  signal: null
13 info lifecycle hackmd@0.5.1~build: Failed to exec build script
14 verbose stack Error: hackmd@0.5.1 build: `webpack --config webpack.production.js --progress --colors --bail`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid hackmd@0.5.1
16 verbose cwd /opt/app
17 error Linux 3.16.0-4-amd64
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error hackmd@0.5.1 build: `webpack --config webpack.production.js --progress --colors --bail`
22 error Exit status 1
23 error Failed at the hackmd@0.5.1 build script 'webpack --config webpack.production.js --progress --colors --bail'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the hackmd package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack --config webpack.production.js --progress --colors --bail
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs hackmd
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls hackmd
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by SISheogorath** [comment] 2017-10-06 20:23
Does the build issues still exist?

Otherwise, it would be nice to add the documentation and the package to the README or Wiki.

**Comment by zeigerpuppy** [comment] 2017-10-06 20:28
I couldn't get it to build yet but will try again in the next month or so (once I finish installing our new servers)

**Comment by SISheogorath** [comment] 2017-12-09 18:28
👋 One how is the state of this? Anything happened?

**Comment by SISheogorath** [comment] 2018-01-23 01:01
Since there is nothing happening here and we can't maintain all of it right now, I'll close this. Feel free to reopen when you made further progress or need feedback or something :)

**Closed by SISheogorath** 2018-01-23 01:01 UTC
Labels: needs info
