### ISSUE TITLE
Deploying without PhantomJS dependency

### ISSUE THREAD

**Issue by a-andreyev** [hackmdio/hackmd#652] opened 2017-12-10 12:36 UTC
Hello! 
I'm trying to deploy hackmd on aarch64.
Not sure is it possible, but looks like I'm having trouble with PhantomJS only.

I've updated `node:6.12.0-alpine` to `node:9.2.0-alpine`
and `postgres:9.6-alpine` to `postgres:10.1-alpine` to support my 64bit arm device.
and uncommented `build:` section at docker-compose with `hackmd:latest-alpine` and `HMD_ALLOW_PDF_EXPORT=false` at environment, but getting:

```
PhantomJS not found on PATH                                                                                                           
Unexpected platform or architecture: linux/arm64                                                                                      
It seems there is no binary available for your platform/architecture                                                                  
Try to install PhantomJS globally
```

I've tried to manually put binary from [mitghi phantomjs arm64 build](https://github.com/mitghi/phantomjs-2.1.1-arm64) to `/usr/bin` via `alpine/Dockerfile` -- no luck (same error)

Any hints? (I'm a noob at docker and nodejs)

P.S.: thank you for your project! :)

**Comment by SISheogorath** [comment] 2017-12-10 13:16
To be honest, there are not many aarch64 deployments around, so happy to see, someone using it. 👍 

The PhantomJS problem is caused by the fact, that it's still a dependency, but with `HMD_ALLOW_PDF_EXPORT=false` no longer used.

But no matter you'll probably run into different issues. Iirc my last tests with Node 8 and HackMD didn't turn out perfectly because of some dependencies but maybe that changes recently.

You can try to fork HackMD, move [this line](https://github.com/hackmdio/hackmd/blob/e9e7a8e23df7e82730b843c748e17072fb2f1221/package.json#L76) to the optional dependencies and update [these lines](https://github.com/hackmdio/docker-hackmd/blob/5324b61fc3b1ae2e9dc553ecf7e5d9671c18d9c7/docker-compose.yml#L28-L29) in your compose file, to use your repository.

If that works, feel free to file a pull request. If not, feel free to further get help here :)

**Comment by a-andreyev** [comment] 2017-12-10 20:40
Thank you for the help!
for now `yarn why phantomjs-prebuilt` returning not only the `markdown-pdf` but `codemirror` too.
Didn't managed to build it with `phantomjs-prebuilt` as optional dependency, hope will investigate more into this task later.

**Comment by SISheogorath** [comment] 2018-01-16 09:18
It is doable. But very hacky. Just write a shellscript and place it in your `PATH`. It should simply return a phantomjs version string. 

See:
https://github.com/Medium/phantomjs/blob/0cc1407f107f8399747015f131390247d0ff60c4/lib/util.js#L47-L61

**Comment by a-andreyev** [comment] 2018-01-21 12:32
@SISheogorath, thank you for the hint,
not sure I could implement it:

I'm adding [this bash script](https://gist.github.com/a-andreyev/2b377418648d343d34e53d247fdace0d) to `/usr/bin` and making it executable.
The result is:
```
...
[4/4] Building fresh packages...
warning
Error running install script for optional dependency: "/usr/local/share/.cache/yarn/v1/.tmp/d0bae1b5a1f45048ee8c0ff9aa923ac7.14afbd8b0d8f8d1e963839edf9fc05f30ab13670.prepare/node_modules/phantomjs-prebuilt:
Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /usr/local/share/.cache/yarn/v1/.tmp/d0bae1b5a1f45048ee8c0ff9aa923ac7.14afbd8b0d8f8d1e963839edf9fc05f30ab13670.prepare/node_modules/phantomjs-prebuilt
Output:
Considering PhantomJS found at /usr/bin/phantomjs
Found PhantomJS at /usr/bin/phantomjs ...verifying
PhantomJS detected, but wrong version 2.1.12 @ /usr/bin/phantomjs.
Unexpected platform or architecture: linux/arm64
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally"
...
```

So looks like I didn't managed to implement the hack and deploy codemirror yet:
```
...
> hackmd@0.5.1 build /hackmd
> webpack --config webpack.production.js --progress --colors --bail

 70% 16/16 b  0% compileModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' /hackmd/node_modules/codemirror/lib/codemirror.css in /hackmd
```

**Comment by SISheogorath** [comment] 2018-06-23 19:51
No further progress into any direction :/ Closing for now.

**Closed by SISheogorath** 2018-06-23 19:51 UTC
Labels: question
