### ISSUE TITLE
Feature request: <details> support

### ISSUE THREAD

**Issue by matthias-vogt** [hackmdio/hackmd#736] opened 2018-02-20 13:41 UTC
I often need code like this
```
<details>
	<summary>Spoiler</summary>
	something happens
</details>
```
<details>
	<summary>Spoiler</summary>
	something happens
</details>
<br>
It would be cool if this was supported natively with some kind of markup.

**Comment by ccoenen** [comment] 2018-02-20 21:57
Duplicate of #445 - but this would be a very nice first contribution! All it takes is a bit of CSS, some testing :-) (demo css also in #445)

**Closed by ccoenen** 2018-02-20 21:57 UTC
