### ISSUE TITLE
Published notes are sometimes loading as 403 Forbidden

### ISSUE THREAD

**Issue by keirwilliams** [hackmdio/hackmd#392] opened 2017-03-18 00:23 UTC
I see the issue when I access the published page on a browser I'm not logged into HackMD on or in a private window.

![403 Forbidden](https://cloud.githubusercontent.com/assets/26045249/24067140/aafd3eb4-0b70-11e7-9062-95f8bb61258d.png)

**Comment by jackycute** [comment] 2017-03-18 07:50
Hi @keirwilliams 
That's mean you have to login to view that page.
It's controlled by the note permission.

**Comment by keirwilliams** [comment] 2017-03-18 08:03
I'm aware but the page permission is set so other people can view it, and
this is a published page, permissions shouldn't affect it.

**Comment by jackycute** [comment] 2017-03-18 08:57
Actually published page still affect by the permission, they're not separated.
Could you tell us your note permission?

**Comment by keirwilliams** [comment] 2017-03-18 09:09
Not what I thought published was then. I thought it created an open
shareable version.

Locked

**Comment by jackycute** [comment] 2017-03-18 09:13
OK, so `Locked` means only the owner can edit the note and everyone else should be able to view it.
It's not normal if you see 403 forbidden in this permission.
Could you provide the note link or send email to hackmdio@gmail.com for conceal.

So the permission is bundled in editor and published page because currently it's the only way to limit the viewers.

**Comment by jackycute** [comment] 2017-03-22 10:34
I'll close this issue for now because we can't reproduce this.
Please reopen if anyone found this happen again.

**Closed by jackycute** 2017-03-22 10:34 UTC
