### ISSUE TITLE
Error with Webpack Plugin

### ISSUE THREAD

**Issue by funkycram** [hackmdio/hackmd#517] opened 2017-07-21 10:52 UTC
After fresh install, on the browser, I have the following error : 

```
Html Webpack Plugin:

  TypeError: Cannot read property '0' of undefined
  
  - ExternalModuleFactoryPlugin.js:19 
    [lib]/[webpack]/lib/ExternalModuleFactoryPlugin.js:19:40
  
  - NormalModuleFactory.js:159 
    [public_html]/[webpack]/lib/NormalModuleFactory.js:159:3
  
  - Tapable.js:75 NormalModuleFactory.applyPluginsAsyncWaterfall
    [public_html]/[tapable]/lib/Tapable.js:75:69
  
  - NormalModuleFactory.js:144 NormalModuleFactory.create
    [public_html]/[webpack]/lib/NormalModuleFactory.js:144:8
  
  - Compilation.js:356 Compilation.process [as _addModuleChain]
    [public_html]/[webpack]/lib/Compilation.js:356:16
  
  - Compilation.js:424 Compilation.process [as addEntry]
    [public_html]/[webpack]/lib/Compilation.js:424:7
  
  - SingleEntryPlugin.js:24 Compiler.compiler.plugin
    [lib]/[webpack]/lib/SingleEntryPlugin.js:24:16
  
  - Tapable.js:107 Compiler.applyPluginsParallel
    [public_html]/[tapable]/lib/Tapable.js:107:14
  
  - Compiler.js:394 Compiler.compile
    [public_html]/[webpack]/lib/Compiler.js:394:7
  
  - Compiler.js:203 Compiler.runAsChild
    [public_html]/[webpack]/lib/Compiler.js:203:7
  
  - compiler.js:70 
    [lib]/[html-webpack-plugin]/lib/compiler.js:70:19
  
  - debuggability.js:300 Promise._execute
    [lib]/[html-webpack-plugin]/[bluebird]/js/release/debuggability.js:300:9
  
  - promise.js:483 Promise._resolveFromExecutor
    [lib]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:483:18
  
  - promise.js:79 new Promise
    [lib]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:79:10
  
  - compiler.js:69 Object.compileTemplate
    [lib]/[html-webpack-plugin]/lib/compiler.js:69:10
  
  - index.js:47 Compiler.
    [lib]/[html-webpack-plugin]/index.js:47:40
  
  - Tapable.js:107 Compiler.applyPluginsParallel
    [public_html]/[tapable]/lib/Tapable.js:107:14
  
  - Compiler.js:394 Compiler.compile
    [public_html]/[webpack]/lib/Compiler.js:394:7
  
  - Compiler.js:173 Compiler.
    [public_html]/[webpack]/lib/Compiler.js:173:9
  
  - Compiler.js:302 Compiler.readRecords
    [public_html]/[webpack]/lib/Compiler.js:302:10
  
  - Compiler.js:170 Compiler.
    [public_html]/[webpack]/lib/Compiler.js:170:8
  
  - Tapable.js:67 Compiler.next
    [public_html]/[tapable]/lib/Tapable.js:67:11
  
  - NodeEnvironmentPlugin.js:23 Compiler.
    [public_html]/[webpack]/lib/node/NodeEnvironmentPlugin.js:23:3
  
  - Tapable.js:69 Compiler.next
    [public_html]/[tapable]/lib/Tapable.js:69:14
  
  - CachePlugin.js:22 Compiler.
    [public_html]/[webpack]/lib/CachePlugin.js:22:58
  
  - Tapable.js:71 Compiler.applyPluginsAsync
    [public_html]/[tapable]/lib/Tapable.js:71:13
  
  - Compiler.js:167 Compiler.run
    [public_html]/[webpack]/lib/Compiler.js:167:7
  
  - MultiCompiler.js:102 
    [public_html]/[webpack]/lib/MultiCompiler.js:102:12
  
  - async.js:356 
    [public_html]/[webpack]/[async]/lib/async.js:356:13
  
  - async.js:233 async.forEachOf.async.eachOf
    [public_html]/[webpack]/[async]/lib/async.js:233:13
  
```
I have installed nvm version 7.5.0
Thanks for your help.

**Comment by SISheogorath** [comment] 2017-10-12 13:05
Can't reproduce with the current master branch. Close this for now. If the error persists feel free to reopen this issue.

**Closed by SISheogorath** 2017-10-12 13:05 UTC
Labels: bug
