### ISSUE TITLE
Offset cursor when in half-screen window

### ISSUE THREAD

**Issue by darrenwee** [hackmdio/hackmd#544] opened 2017-09-11 10:58 UTC
(issue is similar to #127)

The cursor becomes offset by a few lines when I use HackMD as a half-window. I am using Google Chrome `Version 61.0.3163.79 (Official Build) (64-bit)` on Ubuntu 16.04. I use `vim` mode.

![hackmd-buggy](https://user-images.githubusercontent.com/12949331/30271336-827cf77a-9722-11e7-9edf-73ffcca85a0c.png)

Somewhat reliable way to reproduce: open a note on HackMD and snap it to half-window size (I use `Ctrl + Alt + Left Arrow`) and begin typing. Bug appears 80% of the time. Cannot correlate with other reasons for why this doesn't happen *all* the time. The issue disappears when you use HackMD maximized.

It's annoying as I like to take notes on HackMD and look at lecture notes side-by-side on my laptop.

**Comment by ccoenen** [comment] 2017-09-12 08:10
The closest thing to your setup I have is Chromium 60.0.3112.78 / Debian 9.1 in vim Mode, but I can't reproduce it.

One question I asked myself: You're mentioning "happens 80% of the time". what does it need to fix / break it? Does the window size need to change to get the error? Do you have to do a browser reload to get the error? I tried all of these, but perhaps my setup is too different from yours.

**Comment by ccoenen** [comment] 2017-09-12 08:17
one other interesting thing might be the font that's used. In my case that's "Source Code Pro - local file (264 glyphs)".
I found this in Chrom(ium)s Developer tools:
* <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> (to open up the tools)
* "Elements Tab"
* find one of the lines, use the <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd>-Tool to find this by just clicking with the mouse.
* Right side then shows a tab called "computed" (next to "styles")
* all the way at the bottom is "Rendered Fonts")

**Comment by ccoenen** [comment] 2017-09-25 11:13
In case, nobody can confirm this (or give other helpfulk info) I'd close this in about two weeks time.

**Comment by SISheogorath** [comment] 2017-09-25 11:52
I can't say it for sure, but it happened to me, too. But only on mobile devices.

I tried to reproduce it but didn't work. To me it iirc happened when I add a long link at the bottom of a note by pasting. It has been a while since it it happened last time and I'm not 100% sure why and how it appears, but I guess it's part of this monster of cursor JS code what is around. Maybe a timing issue. For sure hard to debug.

**Comment by ccoenen** [comment] 2017-10-06 16:06
I'm closing this for now. Please, everybody, feel free to reopen this if more info becomes available! If it's a bug we can reproduce it will surely get fixed.

**Closed by ccoenen** 2017-10-06 16:06 UTC
