### ISSUE TITLE
Missing release 0.5.2 Affogato

### ISSUE THREAD

**Issue by wenzul** [hackmdio/hackmd#531] opened 2017-08-21 10:24 UTC
When will [0.5.2 Affogato](https://hackmd.io/s/release-notes#052-affogato-2017-06-14-1400) be released in this repo?
I would really like to provide that toolbar for beginners :)

**Comment by ccoenen** [comment] 2017-08-24 10:41
I didn't even know there was a new release! I would also like to update my installation.

**Comment by SISheogorath** [comment] 2017-08-24 16:59
This release is currently not available in this repository. For example, the bookmode is missing. And some other minor changes.

But the current master branch builds fine and is ready to use.

If you need docker build, check https://hub.docker.com/r/sheogorath/docker-hackmd/tags/

**Comment by wenzul** [comment] 2017-08-25 06:39
The question is why it's not availible?

**Comment by xorander00** [comment] 2017-08-25 16:23
Is there a plan to release it or is the project going private?  I respect it either way, but would like to know before I decide for myself how to move forward.  Book mode is actually something that I really want to use in a self-hosted instance.  
  
If the project is still planning a new release, what can we (the community) do to assist?  Thank you for the project and all of the work that went into it.  It's much appreciated :)

**Comment by SISheogorath** [comment] 2017-08-25 17:41
Well, I asked @jackycute for an official statement a few days ago. Didn't happen, so now I take the floor:

From what he told me, the members of the project are currently very short in time. So I guess their priority is currently on keep hackmd.io alive. That's why the current development became very slow and missing some features. My current guess about the book mode is that the implementation is more a hack than clean and since programmers are artists it needs some more work before the source code will be available to the public.

What I do right now is responding to issues and review PRs. I hope our devs will enjoy this work and maybe find a little bit of time to merge these things, once they are ready. Feel free to help me with these tasks.

If it comes to critical problems I'll maybe fork the project and provide some kind of bugfix releases to keep the project alive and active. But that's only an emergency plan right now.

I hope this explains the entire situation a bit. The project is not dead, it's just short on time.

**Comment by xorander00** [comment] 2017-08-25 17:48
@SISheogorath Cool, thanks for the update!  Any chance of getting the book mode feature pushed up in a separate branch or even just a patch?  I totally understand the code not being pretty enough to release, but maybe some of us here can refactor it and eventually get it merged into master after enough review & testing.  

I have a short-list of features for myself that would add a lot of value to the project for my own needs.  I'd be willing to open it up and send a few pull requests when they're ready.  Be forewarned though, I'm short on time as well and I take things on a priority basis.

**Comment by ccoenen** [comment] 2017-08-25 18:28
Anything we can _help_ with on hackmd.io? If that takes up too much of their time, maybe it can be distributed evenly to more people?

**Comment by SISheogorath** [comment] 2017-08-25 18:34
Please keep calm :) There will be an official statement by the HackMD team. I only provided this statement right now to prevent rumors.

I'm not an HackMD official, so I can't provide anything of the hackmd.io source code. But I use and support HackMD so I will keep an eye on all these things :)

I'm sure they appreciate these offers! :+1:

**Comment by SISheogorath** [comment] 2017-08-28 00:50
For those who want to help to get more PRs ready, feel free to review this one: https://github.com/hackmdio/hackmd/pull/462

There is a "vote-wanted" label added so feel free, to use your English skills and review it. Please approve or request changes. But please don't do it blindly. Thanks~

Help material: https://help.github.com/articles/about-pull-request-reviews/

If it's fine for @wenzul I would like to hijack the thread a bit and provide some things we can focus on to make them ready for merging.

**Comment by MartB** [comment] 2017-09-05 15:03
Any news ?

**Comment by tskgw** [comment] 2017-09-06 10:17
I also want to know.

**Comment by xorander00** [comment] 2017-09-26 03:23
This project looks pretty dead, unfortunately.  I do appreciate the effort they've put in so far though.  I've been designing my own system for the last few weeks and will start implementation next week.  It's not exactly analogous to this project, but it is made to replace it for my own uses.  It's going to take a while though as I can only spare a few hours per week to work on it.

**Comment by SISheogorath** [comment] 2017-09-26 11:46
The project is **not** dead. We recently had a conference call with the people running HackMD.io and this repo will continued to developed very soon. I want to leave open why and how because that's something that will be pointed out in an official statement. But I'll be part of it as well as everyone who is interested in participating and developing HackMD.

I know it has been a long time since the last commit to this repository, e.g. 3 month now, which is a way too long, yes, but it's not dead.

Of course, no one will stop you from developing your own solution. But if you're willing to wait for 1 more week, you'll see progress.

**Comment by xorander00** [comment] 2017-09-27 08:28
I'll keep my eye on this project.  I'm going to keep working on my own system as well though, as it's specifically modeled after my usage & workflow.  I may integrate HackMD as the notes feature if the project picks up activity in the interim.  Here's a short-list of stuff that HackMD lacks that I want to implement in my own project:  

- Architectural modifications: RxJS for streams & Service workers for offline use with localForage.
- Behavior update: Throttle/debounce editor input & use command pattern + observer so that it's more performant and more resilient to minor network issues.
- Boolean operators for tag searching to explicitly include/exclude tags in a search expression.
- Better responsiveness & updated card layout to make more efficient use of available viewport width.
  
I'll check out the updates here, and if it's better to integrate HackMD and submit PRs for the changes, I'll do that.

**Comment by ccoenen** [comment] 2017-09-27 12:07
I believe most of these deserve an issue of their own. This way we could discuss them in a more structured manner. I don't know if all of them are possible (I'm not involved with the code of this project) but they all sound like very reasonable suggestions.

**Comment by xorander00** [comment] 2017-09-27 12:18
Once the team makes the upcoming announcement, I'll go through my designs & task lists for my own project.  I'll pull out things that could be implemented in HackMD and look at opening issues here for them.  
  
The first three items in my list above are not trivial, they'll probably be comprised of a series of Issues & PRs.  The last one is a bit simpler since 50%-60% of it comprised of style changes.  The extra functionality bits are not mandatory, they just provide better UX for existing features.  
  
Another major feature is a more powerful and flexible tagging system.  That's actually what I started implementing last weekend and will be looking to finish this weekend.

**Comment by xorander00** [comment] 2017-10-04 09:37
Any announcements?

**Comment by jackycute** [comment] 2017-10-04 09:52
Hi @xorander00,
We'll announce in this week, please give us few more days.
Feel free to PR, we'll continue this project.

**Comment by jackycute** [comment] 2017-10-09 08:47
We still working on it for now, and need to get some responses from people.
So please give us more days.

**Comment by SISheogorath** [comment] 2017-10-09 16:58
For all who are bored by waiting for the announcement, the project is alive and will stay alive. So you can easily start contributing.

Digital Ocean and GitHub announced the [Hacktoberfest](https://hacktoberfest.digitalocean.com/) and allows everyone who participates to get a T-Shirt.

We have various issues [labeled as Hacktoberfest](https://github.com/hackmdio/hackmd/labels/Hacktoberfest) which should be possible to solve this month.

No matter if you want a T-Shirt or not, we would love to see your contributions! ❤️ 

*Pro Tip: If you want to get the T-Shirt (and some stickers) you have to sign up on the Hacktoberfest site.*

**Comment by jackycute** [comment] 2017-10-11 18:32
Hello everybody!
Please read #579 and #580 for announcements.

**Comment by david50407** [comment] 2017-10-17 04:45
@jackycute So, you mean that 0.5.2 is currently part of HackMD Enterprise Edition? 

Or 0.5.2 is currently under AGPL? But we have to wait all committer to sign-off the agreement of changing to AGPL that we can public the codebase of 0.5.2?

**Comment by SISheogorath** [comment] 2017-10-17 06:49
@david50407 hackmd.io is currently running a closed source fork of this code base. In this repository there will be no release named 0.5.2.

We will relicense this repository and release 1.0.0-ce under AGPL.

if not everybody makes it to sign the License Change agreement we will keep their Code under MIT and will mark these files with a license header so everyone can see what parts of the code are currently under MIT license and which are AGPL. 

As soon as these contributions that prevent a file from being AGPL are no longer part of a file because the code got refactored or was removed in another way, these files are licensed under AGPL, too.

But we try to get all people to sign the agreement since it simplifies the hole licensing a lot.

**Comment by david50407** [comment] 2017-10-17 07:11
@SISheogorath So is hackmd.io running some thing like a EE pre-released version? Or the features will be merge back to 1.0.0-CE?

As I know, if a project is under AGPL, the whole project must be licensed under AGPL.
That means "The MIT part" wouldn't keep under MIT if HackMD switched to AGPL.

I know that the MIT License allows a fork with another license without agreement by contributors, but this seems kind a little bit harms of open source spirit.

I know that HackMD CE (this project) still accepting pull requests, but other contributors/users cannot get which features on hackmd.io will be merge to CE, or the hackmd.io is running EE version (that means new features on 0.5.2 will possibly not be merged to CE)? 

This confused me that HackMD team [announced](https://hackmd.io/c/community-news/https%3A%2F%2Fhackmd.io%2Fs%2FBk-zpEC9-) that we have new EE playground on demo.hackmd.io. But how about the original hackmd.io? Is this switched to EE already? Or will this still running CE version and all features in 0.5.2 will be shows on GitHub publicly soon?

**Comment by SISheogorath** [comment] 2017-10-17 07:44
> So is hackmd.io running something like an EE pre-released version? Or the features will be merged back to 1.0.0-CE?

Yes, HackMD.io runs a pre-release of HackMD EE and features like the book mode will not be part of HackMD CE as long as no one of the community feels the need to implement it himself/herself.

HackMD CE is not about to follow HackMD EE like reimplementing all their features. We want to go an own way with a different focus. Right now, I (personally) would like to focus on self-hosting features for HackMD CE, including the upcoming #345  for Minio support and nice collaboration features.

> As I know, if a project is under AGPL, the whole project must be licensed under AGPL.
That means "The MIT part" wouldn't keep under MIT if HackMD switched to AGPL.

It is possible, but it's very complicated. If we can't bring people to re-license their code we have to keep them as MIT code. Since you can have different licenses per file, it's actually possible, MIT is compatible with AGPL so we don't run into a problem here.

All new changes are licensed as AGPL while the not re-licensed code is kept as MIT (and will be removed from the repository over time).

> I know that the MIT License allows a fork with another license without agreement by contributors, but this seems kind a little bit harms of open source spirit.

The MIT license allows sublicensing which means you are allowed to use the code together with a more copyleft as well as more proprietary license. But you have to include an MIT license file into the software and you can't simple re-license the code itself. Which also means you have to point out which parts are written under MIT license and give credit to the author. So we **have to** keep the MIT license until we remove the not re-licensed code in these files as we don't want to violate any rights of the authors. 

---

Yes, none of the features added to HackMD.io which are not already part of this repository will make it into HackMD CE for now. I can't speak for the HackMD team in general so maybe they have different plans. @GitOnion knows the details about what is going where.

---

In general, to keep the discussion itself in this thread on a not too annoying level for all followers, feel free to discuss this with me and others in our [Gitter channel](https://gitter.im/hackmdio/hackmd).

**Comment by SISheogorath** [comment] 2017-10-31 13:15
Since the License change is coming soon and this way HackMD CE will release soon, we should maybe talk about release strategies and versioning.

 The upcoming release will be HackMD 1.0.0-CE and we will probably continue using SemVer (at least that's my plan, but I'm open for ideas).

I think we should start to stabilize releases by providing a bugfix branch and using the master a dev branch. As you may have noticed the past few days, there was a lot broken and I pushed some hotfixes after merging new features. That's ugly but caused by the fact that currently there is a big lack of developer documentation and tests. #611  tries to get some input for that.

I also started some developer documentation but it's more like a write up for now. It's neither complete nor ready to be merged anywhere. But feel free to read and extend it:

https://hackmd.io/EYZgLAJgZgHAjAUwLQFZ5yWAbAQwwThBgHZMsQcEph8ocwcg#

I would love to get some input on this and I think in order to make these decisions in future it would be awesome to have a community that really talks and not only creates issues and pull requests 😉 

Right now there is [Gitter](https://gitter.im/hackmdio/hackmd) but I'm also open for an alternative.

Regards

**Comment by ccoenen** [comment] 2017-10-31 21:49
:+1: for SemVer. I think you'd have to have exeptionally good reasons to go against the de-facto standard on NPM.

**Comment by SISheogorath** [comment] 2017-12-07 11:22
Since we have the license change agreement merged now it's time to do a release.

I would like to make this happen ins December since it has been long enough, but this needs help from our community :)

We have the [1.0.0-CE Milstone](https://github.com/hackmdio/hackmd/milestone/13) to see what will make it into this. I hope you'll help to make it happen and review your own PRs about what is needed. 

One new feature that would be nice and some docs jobs. That's the main work :) And thanks for all your contributions!

**Comment by SISheogorath** [comment] 2018-01-18 16:03
1.0.0-ce was released.

It's nice to work with you guys and hope a lot releases will follow soon 👍

**Closed by SISheogorath** 2018-01-18 16:03 UTC
Labels: HackMD.io, question
